import React from 'react';
import './css/About.css'
import aboutus from './img/about-us.png';
import paragraphBreak from './img/paragraph-break.png';
import Footer from './Footer';
const TermsOfService = () => {
    return (
        <>
         <div className='about'>
         <div className='about-body'>
                <div className='about-text-container'>
                    <h2 id='title'>Terms of Service</h2>
                    <h3>Intellectual Property Rights</h3>
                    <p>The products of RevYou are protected by the laws of copyright and trademark. RevYou may include a digital watermark embedded in the outputs it shall generate to keep track of the usage of the service if ever showcased outside of the RevYou website. </p>
                    <img src= {paragraphBreak}></img>
                </div>
                
                <div className='about-text-container'>
                    <h3>Data protection</h3>
                        <p> RevYou will not be collecting any additional classification of the user’s personal data. Under no circumstances shall RevYou make use of the user’s personal data for any separate or irreconcilable purpose without providing the user any consent. </p>
                        <img src= {paragraphBreak}></img>
                </div>

                <div className='about-text-container'>
                    <h3>Generated content </h3>
                    <p>RevYou will not be collecting any additional classification of the user’s personal data. Under no circumstances shall RevYou make use of the user’s personal data for any separate or irreconcilable purpose without providing the user any consent. </p>
                    <img src= {paragraphBreak}></img>
                </div>

                <div className='about-text-container'>
                    <h3>Acceptable use policy</h3>
                    <p>The user shall use RevYou to submit inputs and be given outputs generated by the summarizing tool. Whatever input the user submits and the outputs that they receive are accounted as User Data. The user shall be responsible for any activity in connection with their User Data. The RevYou parties shall not be liable for any illegal and inappropriate activity by the user that not only violates our rights but also the rights of any third party.</p>
                    <img src= {paragraphBreak}></img>
                </div>

                <div className='pic-container'>
                    <img src={aboutus}></img>
                </div>
            </div>
         </div>
         <Footer />
        </>
       
    );
  };

export default TermsOfService;